<?xml version="1.0" encoding="UTF-8"?><testrun duration="8230" footerText="Generated by IntelliJ IDEA on 25/08/24, 12:16â€¯pm" name="ServiceImplTest">
    <count name="total" value="51"/>
    <count name="passed" value="51"/>
    <config nameIsGenerated="true" configId="JUnit" name="ServiceImplTest">
        <module name="HospitalManagementSystemWebApp"/>
        <extension name="coverage">
            <pattern>
                <option name="PATTERN" value="com.hospital.service.*"/>
                <option name="ENABLED" value="true"/>
            </pattern>
        </extension>
        <option name="PACKAGE_NAME" value="com.hospital.service"/>
        <option name="MAIN_CLASS_NAME" value="com.hospital.service.ServiceImplTest"/>
        <option name="TEST_OBJECT" value="class"/>
        <method v="2">
            <option name="Make" enabled="true"/>
        </method>
    </config>
    <root name="ServiceImplTest" comment="com.hospital.service" location="java:suite://com.hospital.service.ServiceImplTest">
        <output type="stdout">E:\java_17\bin\java.exe -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:E:\IntelliJ IDEA 2024.2.0.1\lib\idea_rt.jar=61954:E:\IntelliJ IDEA 2024.2.0.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\Users\User\.m2\repository\org\junit\platform\junit-platform-launcher\1.10.0\junit-platform-launcher-1.10.0.jar;E:\IntelliJ IDEA 2024.2.0.1\lib\idea_rt.jar;E:\IntelliJ IDEA 2024.2.0.1\plugins\junit\lib\junit5-rt.jar;E:\IntelliJ IDEA 2024.2.0.1\plugins\junit\lib\junit-rt.jar;E:\Hospital-Management-System\HospitalManagementSystemWebApp\target\test-classes;E:\Hospital-Management-System\HospitalManagementSystemWebApp\target\classes;C:\Users\User\.m2\repository\jakarta\servlet\jakarta.servlet-api\6.0.0\jakarta.servlet-api-6.0.0.jar;C:\Users\User\.m2\repository\org\junit\jupiter\junit-jupiter-api\5.10.0\junit-jupiter-api-5.10.0.jar;C:\Users\User\.m2\repository\org\opentest4j\opentest4j\1.3.0\opentest4j-1.3.0.jar;C:\Users\User\.m2\repository\org\junit\platform\junit-platform-commons\1.10.0\junit-platform-commons-1.10.0.jar;C:\Users\User\.m2\repository\org\apiguardian\apiguardian-api\1.1.2\apiguardian-api-1.1.2.jar;C:\Users\User\.m2\repository\org\junit\jupiter\junit-jupiter-engine\5.10.0\junit-jupiter-engine-5.10.0.jar;C:\Users\User\.m2\repository\org\junit\platform\junit-platform-engine\1.10.0\junit-platform-engine-1.10.0.jar;C:\Users\User\.m2\repository\com\mysql\mysql-connector-j\8.0.33\mysql-connector-j-8.0.33.jar;C:\Users\User\.m2\repository\com\google\protobuf\protobuf-java\3.21.9\protobuf-java-3.21.9.jar;C:\Users\User\.m2\repository\log4j\log4j\1.2.12\log4j-1.2.12.jar;C:\Users\User\.m2\repository\org\json\json\20240303\json-20240303.jar;C:\Users\User\.m2\repository\org\mockito\mockito-junit-jupiter\5.10.0\mockito-junit-jupiter-5.10.0.jar;C:\Users\User\.m2\repository\org\mockito\mockito-core\5.10.0\mockito-core-5.10.0.jar;C:\Users\User\.m2\repository\net\bytebuddy\byte-buddy\1.14.11\byte-buddy-1.14.11.jar;C:\Users\User\.m2\repository\net\bytebuddy\byte-buddy-agent\1.14.11\byte-buddy-agent-1.14.11.jar;C:\Users\User\.m2\repository\org\objenesis\objenesis\3.3\objenesis-3.3.jar" com.intellij.rt.junit.JUnitStarter -ideVersion5 -junit5 com.hospital.service.ServiceImplTest
Process finished with exit code 0
</output>
    </root>
    <test duration="4924" locationUrl="java:test://com.hospital.service.ServiceImplTest/testGetAllPatient" name="testGetAllPatient()" metainfo="" status="passed">
        <output type="stderr">Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
</output>
    </test>
    <test duration="101" locationUrl="java:test://com.hospital.service.ServiceImplTest/testAddAuthUser2" name="testAddAuthUser2()" metainfo="" status="passed"/>
    <test duration="46" locationUrl="java:test://com.hospital.service.ServiceImplTest/testDeleteAuthUser" name="testDeleteAuthUser()" metainfo="" status="passed"/>
    <test duration="70" locationUrl="java:test://com.hospital.service.ServiceImplTest/testSearchPatient" name="testSearchPatient()" metainfo="" status="passed"/>
    <test duration="35" locationUrl="java:test://com.hospital.service.ServiceImplTest/testSearchUser" name="testSearchUser()" metainfo="" status="passed"/>
    <test duration="20" locationUrl="java:test://com.hospital.service.ServiceImplTest/testSearchUser2" name="testSearchUser2()" metainfo="" status="passed"/>
    <test duration="41" locationUrl="java:test://com.hospital.service.ServiceImplTest/testLogin" name="testLogin()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 560 - Error Occured at Service Layer: Invalid username or Password
[ERROR] main ServiceImpl : 561 - com.hospital.exception.DatabaseException: Invalid username or Password
</output>
    </test>
    <test duration="1024" locationUrl="java:test://com.hospital.service.ServiceImplTest/testSearchAppointment" name="testSearchAppointment()" metainfo="" status="passed"/>
    <test duration="203" locationUrl="java:test://com.hospital.service.ServiceImplTest/testUpdateSchedule" name="testUpdateSchedule()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 310 - Schedule already exists for Date: 1970-01-01 and Time: 00:00 - 00:00
</output>
    </test>
    <test duration="96" locationUrl="java:test://com.hospital.service.ServiceImplTest/testViewAppointments2" name="testViewAppointments2()" metainfo="" status="passed"/>
    <test duration="21" locationUrl="java:test://com.hospital.service.ServiceImplTest/testSearchAppointment2" name="testSearchAppointment2()" metainfo="" status="passed"/>
    <test duration="26" locationUrl="java:test://com.hospital.service.ServiceImplTest/testSearchAppointment3" name="testSearchAppointment3()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 543 - Error Occured at Service Layer: Patient not present with id: 1
[ERROR] main ServiceImpl : 544 - com.hospital.exception.DatabaseException: Patient not present with id: 1
</output>
    </test>
    <test duration="20" locationUrl="java:test://com.hospital.service.ServiceImplTest/testGetAllPatient2" name="testGetAllPatient2()" metainfo="" status="passed"/>
    <test duration="26" locationUrl="java:test://com.hospital.service.ServiceImplTest/testAddPatient2" name="testAddPatient2()" metainfo="" status="passed"/>
    <test duration="22" locationUrl="java:test://com.hospital.service.ServiceImplTest/testAddPatient3" name="testAddPatient3()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 196 - Patient with id 1 already exists
</output>
    </test>
    <test duration="18" locationUrl="java:test://com.hospital.service.ServiceImplTest/testGetAllAuthUser2" name="testGetAllAuthUser2()" metainfo="" status="passed"/>
    <test duration="11" locationUrl="java:test://com.hospital.service.ServiceImplTest/testGetAllAuthUser3" name="testGetAllAuthUser3()" metainfo="" status="passed"/>
    <test duration="19" locationUrl="java:test://com.hospital.service.ServiceImplTest/testGetAllAuthUser" name="testGetAllAuthUser()" metainfo="" status="passed"/>
    <test duration="30" locationUrl="java:test://com.hospital.service.ServiceImplTest/testAddAuthUser" name="testAddAuthUser()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 74 - Username already exists
</output>
    </test>
    <test duration="94" locationUrl="java:test://com.hospital.service.ServiceImplTest/testViewAppointments" name="testViewAppointments()" metainfo="" status="passed"/>
    <test duration="48" locationUrl="java:test://com.hospital.service.ServiceImplTest/testBookAppointment" name="testBookAppointment()" metainfo="" status="passed"/>
    <test duration="280" locationUrl="java:test://com.hospital.service.ServiceImplTest/testCancelAppointment2" name="testCancelAppointment2()" metainfo="" status="passed"/>
    <test duration="22" locationUrl="java:test://com.hospital.service.ServiceImplTest/testCancelAppointment3" name="testCancelAppointment3()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 426 - Appointment doesnt exist with ID: 1
</output>
    </test>
    <test duration="23" locationUrl="java:test://com.hospital.service.ServiceImplTest/testCancelAppointment4" name="testCancelAppointment4()" metainfo="" status="passed"/>
    <test duration="78" locationUrl="java:test://com.hospital.service.ServiceImplTest/testCancelAppointment5" name="testCancelAppointment5()" metainfo="" status="passed"/>
    <test duration="30" locationUrl="java:test://com.hospital.service.ServiceImplTest/testCancelAppointment6" name="testCancelAppointment6()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 440 - Error Occured at Service Layer: An error occurred
[ERROR] main ServiceImpl : 441 - com.hospital.exception.DatabaseException: An error occurred
</output>
    </test>
    <test duration="176" locationUrl="java:test://com.hospital.service.ServiceImplTest/testCancelAppointment7" name="testCancelAppointment7()" metainfo="" status="passed"/>
    <test duration="33" locationUrl="java:test://com.hospital.service.ServiceImplTest/testCancelAppointment8" name="testCancelAppointment8()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 460 - Unauthoried access to cancel the Appointment: AppointmentTbl{AppointmentId=1, patient=PatientTbl{PatientId=1, name='String', email='String', mobileNo='String', addedByUser=AuthUserTbl{UserId=1, name='String', email='String', mobileNo='String', username='String', password='b2ef230e7f4f315a28cdcc863028da31f7110f3209feb76e76fed0f37b3d8580', role='String'}}, schedule=ScheduleTbl{ScheduleId=1, Doctor=AuthUserTbl{UserId=1, name='String', email='String', mobileNo='String', username='String', password='b2ef230e7f4f315a28cdcc863028da31f7110f3209feb76e76fed0f37b3d8580', role='String'}, scheduleDate=1970-01-01, startTime=00:00, endTime=00:00, scheduleStatus=1, unavailabilityReason='String'}, suggestedTests='String', suggestedMedicines='String', sufferingFromDisease='String', appointmentStatus=1} by Doctor: AuthUserTbl{UserId=1, name='null', email='null', mobileNo='null', username='janedoe', password='e4ad93ca07acb8d908a3aa41e920ea4f4ef4f26e7f86cf8291c5db289780a5ae', role='null'}
</output>
    </test>
    <test duration="15" locationUrl="java:test://com.hospital.service.ServiceImplTest/testCancelAppointment9" name="testCancelAppointment9()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 455 - Appointment doesnt exist with ID: 1
</output>
    </test>
    <test duration="23" locationUrl="java:test://com.hospital.service.ServiceImplTest/testSearchSchedule" name="testSearchSchedule()" metainfo="" status="passed"/>
    <test duration="19" locationUrl="java:test://com.hospital.service.ServiceImplTest/testBookAppointment2" name="testBookAppointment2()" metainfo="" status="passed"/>
    <test duration="45" locationUrl="java:test://com.hospital.service.ServiceImplTest/testBookAppointment3" name="testBookAppointment3()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 288 - Error Occured at Service Layer: Patient not found with ID: 1
[ERROR] main ServiceImpl : 289 - com.hospital.exception.DatabaseException: Patient not found with ID: 1
</output>
    </test>
    <test duration="9" locationUrl="java:test://com.hospital.service.ServiceImplTest/testAddPatient" name="testAddPatient()" metainfo="" status="passed"/>
    <test duration="11" locationUrl="java:test://com.hospital.service.ServiceImplTest/testAddSchedule2" name="testAddSchedule2()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 135 - Doctor with id 1 not found
</output>
    </test>
    <test duration="15" locationUrl="java:test://com.hospital.service.ServiceImplTest/testAddSchedule3" name="testAddSchedule3()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 145 - Schedule already exists
</output>
    </test>
    <test duration="15" locationUrl="java:test://com.hospital.service.ServiceImplTest/testAddSchedule4" name="testAddSchedule4()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 150 - You cannot add schedule for past date
</output>
    </test>
    <test duration="12" locationUrl="java:test://com.hospital.service.ServiceImplTest/testAddSchedule5" name="testAddSchedule5()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 155 - Schedule start time should be between 9AM to 6PM
</output>
    </test>
    <test duration="24" locationUrl="java:test://com.hospital.service.ServiceImplTest/testUpdateSchedule2" name="testUpdateSchedule2()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 305 - Doctor with id 1 not found
</output>
    </test>
    <test duration="12" locationUrl="java:test://com.hospital.service.ServiceImplTest/testUpdateSchedule3" name="testUpdateSchedule3()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 300 - Schedule with id 0 not found
</output>
    </test>
    <test duration="30" locationUrl="java:test://com.hospital.service.ServiceImplTest/testUpdateSchedule4" name="testUpdateSchedule4()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 315 - You cannot add schedule for past date
</output>
    </test>
    <test duration="11" locationUrl="java:test://com.hospital.service.ServiceImplTest/testUpdateAuthUser" name="testUpdateAuthUser()" metainfo="" status="passed"/>
    <test duration="23" locationUrl="java:test://com.hospital.service.ServiceImplTest/testNewServiceImpl" name="testNewServiceImpl()" metainfo="" status="passed"/>
    <test duration="96" locationUrl="java:test://com.hospital.service.ServiceImplTest/testCancelAppointment10" name="testCancelAppointment10()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 460 - Unauthoried access to cancel the Appointment: AppointmentTbl{AppointmentId=1, patient=PatientTbl{PatientId=1, name='String', email='String', mobileNo='String', addedByUser=AuthUserTbl{UserId=1, name='String', email='String', mobileNo='String', username='String', password='b2ef230e7f4f315a28cdcc863028da31f7110f3209feb76e76fed0f37b3d8580', role='String'}}, schedule=ScheduleTbl{ScheduleId=1, Doctor=AuthUserTbl{UserId=32, name='String', email='String', mobileNo='String', username='String', password='b2ef230e7f4f315a28cdcc863028da31f7110f3209feb76e76fed0f37b3d8580', role='String'}, scheduleDate=1970-01-01, startTime=00:00, endTime=00:00, scheduleStatus=1, unavailabilityReason='String'}, suggestedTests='String', suggestedMedicines='String', sufferingFromDisease='String', appointmentStatus=1} by Doctor: AuthUserTbl{UserId=1, name='null', email='null', mobileNo='null', username='janedoe', password='e4ad93ca07acb8d908a3aa41e920ea4f4ef4f26e7f86cf8291c5db289780a5ae', role='null'}
</output>
    </test>
    <test duration="30" locationUrl="java:test://com.hospital.service.ServiceImplTest/testCancelAppointment11" name="testCancelAppointment11()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 460 - Unauthoried access to cancel the Appointment: AppointmentTbl{AppointmentId=1, patient=PatientTbl{PatientId=1, name='String', email='String', mobileNo='String', addedByUser=AuthUserTbl{UserId=1, name='String', email='String', mobileNo='String', username='String', password='b2ef230e7f4f315a28cdcc863028da31f7110f3209feb76e76fed0f37b3d8580', role='String'}}, schedule=ScheduleTbl{ScheduleId=1, Doctor=AuthUserTbl{UserId=1, name='String', email='String', mobileNo='String', username='String', password='b2ef230e7f4f315a28cdcc863028da31f7110f3209feb76e76fed0f37b3d8580', role='String'}, scheduleDate=1970-01-01, startTime=00:00, endTime=00:00, scheduleStatus=1, unavailabilityReason='String'}, suggestedTests='String', suggestedMedicines='String', sufferingFromDisease='String', appointmentStatus=1} by Doctor: null
</output>
    </test>
    <test duration="49" locationUrl="java:test://com.hospital.service.ServiceImplTest/testAddSchedule" name="testAddSchedule()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 140 - User is not a doctor
</output>
    </test>
    <test duration="13" locationUrl="java:test://com.hospital.service.ServiceImplTest/testDeleteAuthUser2" name="testDeleteAuthUser2()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 112 - AuthUser with id 1 not found
</output>
    </test>
    <test duration="12" locationUrl="java:test://com.hospital.service.ServiceImplTest/testDeleteAuthUser3" name="testDeleteAuthUser3()" metainfo="" status="passed"/>
    <test duration="76" locationUrl="java:test://com.hospital.service.ServiceImplTest/testCancelAppointment" name="testCancelAppointment()" metainfo="" status="passed"/>
    <test duration="45" locationUrl="java:test://com.hospital.service.ServiceImplTest/testSearchSchedule2" name="testSearchSchedule2()" metainfo="" status="passed"/>
    <test duration="16" locationUrl="java:test://com.hospital.service.ServiceImplTest/testSearchPatient2" name="testSearchPatient2()" metainfo="" status="passed"/>
    <test duration="92" locationUrl="java:test://com.hospital.service.ServiceImplTest/testSearchPatient3" name="testSearchPatient3()" metainfo="" status="passed">
        <output type="stdout">[ERROR] main ServiceImpl : 509 - Error Occured at Service Layer: User not present with id: 1
[ERROR] main ServiceImpl : 510 - com.hospital.exception.DatabaseException: User not present with id: 1
</output>
    </test>
</testrun>
